# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno and run tests across stable and canary builds on Windows, Ubuntu and macOS.
# For more information see: https://github.com/denoland/setup-deno

name: First-Github-actions
env:
  APLICATION_NAME: "Mytodo"
  PAKAGE_NAME    : "todo-deploy-ver-${{ github.sha }}"

on:
  push:
    branches: 
      - master
    
jobs:
  my_testing:
    
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello-Massage
        run : echo "Hello World from testing job"
       
      - name: Some message 
        run : |
          echo "Hello World1"
          echo "Hello World2"
          echo "Hello World3"
          echo "Aplication name: ${{ env.APLICATION_NAME }}"
          
      - name: list curent folder
        run : ls -la
  
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my_testing]
        
    steps:
      - name: Print Hello-Massage
        run : echo "Hello World from deploy job"
        
        
      - name: Printing Depoyment package 
        run : echo "Deploy package name is ${{ env.PAKAGE_NAME }}"
